[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
dockerfileTarget = "runner"
watchPatterns = ["**"]

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
