[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.web"
dockerfileTarget = "runner"
watchPatterns = ["frontend/**", "Dockerfile.web"]

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
