[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
dockerfileTarget = "runner"

[deploy]
startCommand = "./docker-entrypoint.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
