export const ApiErrorCode = {
  EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  FAVORITE_ALREADY_EXISTS: 'FAVORITE_ALREADY_EXISTS',
  FAVORITE_NOT_FOUND: 'FAVORITE_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  WORD_NOT_FOUND: 'WORD_NOT_FOUND',
  AUDIO_NOT_FOUND: 'AUDIO_NOT_FOUND',
  INVALID_CURSOR: 'INVALID_CURSOR',
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  DICTIONARY_SERVICE_UNAVAILABLE: 'DICTIONARY_SERVICE_UNAVAILABLE',
  AUDIO_SERVICE_UNAVAILABLE: 'AUDIO_SERVICE_UNAVAILABLE',
} as const;

export type ApiErrorCode = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];
